### ISSUE TITLE
How to fix Lua problem

### ISSUE THREAD

**Issue by giomke** [pentesteracademy/patoolkit#3]
I have the latest version of Wireshark. I copied the "plugins" directory to Wireshark plugins directory.
![capture](https://user-images.githubusercontent.com/19889044/50418993-e178c780-0847-11e9-911a-174a3460cad0.PNG)

**Comment by wifisecguy** [comment]
Hi giomke,
It should work but lets try the alternative:
Please try to copy the plugins directory to **Personal plugins** directory (%appdata%\Wireshark).  I just tested it with latest Wireshark (WIndows x64) and it is working for me. If you still face problems, let me know.
Thanks!

**Comment by ITh4cker** [comment]
> **s**

yeah,it works,thank you~

**Comment by wifisecguy** [comment]
Hi @ITh4cker , will it be possible for you to share your PCAP? My understanding is that your PCAP has either a malformed packet or something which is not handled in the code.

If it is not possible to share the PCAP, please let us know what packet is present on number 184222.  Please also paste a detailed screenshot of that packet.

**Comment by giomke** [comment]
> Hi giomke,
> It should work but lets try the alternative:
> Please try to copy the plugins directory to **Personal plugins** directory (%appdata%\Wireshark). I just tested it with latest Wireshark (WIndows x64) and it is working for me. If you still face problems, let me know.
> Thanks!

Thanks, it worked

**Comment by ITh4cker** [comment]
> Hi @ITh4cker , will it be possible for you to share your PCAP? My understanding is that your PCAP has either a malformed packet or something which is not handled in the code.
> 
> If it is not possible to share the PCAP, please let us know what packet is present on number 184222. Please also paste a detailed screenshot of that packet.

hello.sir，I downloaded the pacp from  https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.015944000000000.pcap.gz   you can download it to check if it works~
